### ISSUE TITLE
`curry` and `compose` are not type safe

### ISSUE THREAD

**Issue by DenisFrezzato** [drizzer14/fnts#16]
**Describe the bug**
`curry` and `compose` are not type safe with functions with type variables.

[**To Reproduce**](https://codesandbox.io/s/sparkling-frog-mtnvc?file=/src/index.ts)

**Expected behavior**
I expect the resulting function to have the expected signature.

**Possible ways or ideas to fix** (if any)
I'm not aware of any way to make them work, so the only option is to deprecate them.

**Comment by drizzer14** [comment]
Hi!

I'm of this being a thing and don't have a proper solution atm (and not sure if there's one anyway). But I'll definitely take a look at generics at these types, maybe there is indeed a work-around.

If there's not, I still do want to deprecate them. At least will leave a proper explanation on where and how they can be used, or provide alternatives.

Thanks anyways, leaving this issue open for investigation.

**Comment by drizzer14** [comment]
I've tried playing around with the code you'd provided. Seems like the [issue](https://github.com/microsoft/TypeScript/issues/30369) with the TS itself, mentioned in fp-ts [discussion](https://github.com/gcanti/fp-ts/issues/1644#issuecomment-1003418193), really does not allow for generic functions to work in the contexts of both `curry` and `compose`/`pipe` (or general "generic inheritance", if you will).

The only real workaround for now is to manually annotate the types:
- using type assertions with `unknown` types;
- using explicit annotations with `any` types;

[Applied](https://codesandbox.io/s/great-cray-o2t03?file=/src/index.ts) this ^ to your reproduction and it kinda works, although looking too overkill for such seemingly simple operations.

---

Also, looks like the same issue [is there](https://codesandbox.io/s/loving-paper-suf4p?file=/src/index.ts) in fp-ts (although I may be wrong here, don't know much about the library's API).

---

I'm ok with leaving those functions as is for now, until there are new possibilities in TS to further explore this functionality. Will add proper documentation about this problem, though.

Thanks!

**Comment by DenisFrezzato** [comment]
> Applied this ^ to your reproduction and it kinda works, although looking too overkill for such seemingly simple operations.

Those are not annotations, they are casts, which are unsafe.

> Also, looks like the same issue is there in fp-ts (although I may be wrong here, don't know much about the library's API).

For that use case you want to use `flow` (which composes functions), not `pipe` (which mimics the pipe operator). [Updated playground](https://codesandbox.io/s/cool-black-7nhoz?file=/src/index.ts).

> Thanks!

You're welcome! :slightly_smiling_face:

**Comment by drizzer14** [comment]
Per annotations I mean this:

```
(b**: boolean**) => b.toString(),
(x**: number**) => x > 0
```

**Comment by DenisFrezzato** [comment]
Ah sorry, I was looking at other differences then.
